<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.416.6" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PepperX.Core\PepperX.Core.csproj" />
    <ProjectReference Include="..\PepperX.Server\PepperX.Server.csproj" />
  </ItemGroup>

</Project>
