<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>PepperX core: domain model, metadata database, extent storage, and services.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="PrettyId" Version="2.0.1" />
    <PackageReference Include="SerializationHelper" Version="2.0.3" />
    <PackageReference Include="SyslogLogging" Version="2.1.0" />
  </ItemGroup>

</Project>
